### ISSUE TITLE
logstash-5.1.1: NoMethodError: undefined method `info' for Jars:Module

### ISSUE THREAD

**Issue by gjelu** [mkristian/jar-dependencies#51]
Hi,

This is linked to #https://github.com/elastic/logstash/issues/6396

After installing jar-depedencies-0.3.8 we receive the following error:

NoMethodError: undefined method `info' for Jars:Module

Full output attached:
[console_output.txt](https://github.com/mkristian/jar-dependencies/files/675273/console_output.txt)

**Comment by cpiment** [comment]
Hi,

I'm getting the same error

Centos 7.2
JRuby: jruby 9.1.6.0 (2.3.1) 2016-11-09 0150a76 Java HotSpot(TM) 64-Bit Server VM 25.111-b14 on 1.8.0_111-b14 +jit [linux-x86_64]
Bundle: Bundler version 1.13.7

Complete verbose output: 
[bundle_install_log.txt](https://github.com/mkristian/jar-dependencies/files/682397/bundle_install_log.txt)

**Comment by cpiment** [comment]
I made these changes and now it seems to work. It shows a Warning because I have a settings.xml Maven file with proxy settings:

https://github.com/cpiment/jar-dependencies/commit/e7f5c004e3f24194af8b65a386b0039b37cdd574

Do you want me to send it as PR?

Regards
Carlos

**Comment by mkristian** [comment]
@cpiment I did not see your patch before I did my patch yesterday. if the latest still does not work please feel free to make a PR I will release it asap then.

**Comment by cpiment** [comment]
@mkristian Don't worry, it works with 0.3.9 version :). Thank you!
